export type IdRef = {
  id: string
}

export type World = {
  id: string
  title: string
  genre: string
  narrativeStyle?: string
  tone: string
  synopsis: string
  introNarrative?: string       // rich story introduction generated at world creation (up to 1000 chars)
  startingLocationId?: string   // location where the adventure begins (linked to Act 1)
  acts: Act[]
  locations: LocationRef[]
  finalObjective: string
  createdAt: string
  mapUrl?: string
}

export type ActMission = {
  id: string
  title: string
  description: string
  narrativeDirection: string   // what completing this advances in the story
  linkedNpcNames: string[]     // key NPCs involved
  completed: boolean
}

export type ActKeyNpc = {
  name: string
  role: string                 // e.g. "aliado", "vilao", "mentor", "mercador"
}

export type Act = {
  id: string
  title: string
  goal: string
  missions: ActMission[]       // min 3 per act — define when act is complete
  keyNpcs: ActKeyNpc[]         // important characters for this act
  linkedLocations: LocationRef[]
  requiredActId?: string       // previous act that must be completed first (null for Act 1)
}

export type Location = {
  id: string
  worldId?: string
  name: string
  type: string
  description?: string
  dangerLevel: number
  storyRelevance: 'main' | 'side'
  linkedActs: ActRef[]
  imageUrl?: string
  unlockedByActId?: string     // location is locked until this act is completed (undefined = always open)
}

/* ── Lightweight summaries (generated by LocationArchitect) ── */

export type NpcSummary = {
  id: string
  name: string
  role: string
  description: string
  narrativeEffect?: string
}

export type QuestSummary = {
  id: string
  title: string
  type: 'main' | 'side' | 'ambient'
  description: string
  narrativeEffect?: string
}

export type EnemySummary = {
  id: string
  name: string
  description: string
  narrativeEffect?: string
}

export type ItemSummary = {
  id: string
  name: string
  type: EquipmentType
  description: string
  narrativeEffect?: string
}

/* ── LocationContent (uses lightweight summaries) ── */

export type LocationContent = {
  id: string
  locationId: string
  npcs: NpcSummary[]
  quests: {
    main: QuestSummary[]
    side: QuestSummary[]
    ambient: QuestSummary[]
  }
  enemies: EnemySummary[]
  items: ItemSummary[]
  narrativeImpact: string
}

/* ── Full detail types (generated on-demand by dedicated agents) ── */

export type Quest = {
  id: string
  title: string
  type: 'main' | 'side' | 'ambient'
  description: string
  linkedActIds: string[]
  rewards: Reward[]
  impact: string
}

export type Enemy = {
  id: string
  name: string
  hp: number
  maxHp: number
  level: number
  behavior: string
  attackPattern: string
  drops: Drop[]
  battleAttributes: BattleAttributes
  skills: BattleSkill[]
  aiPattern: EnemyAIPattern
  portraitUrl?: string
}

export type EnemyAIPattern = 'agressivo' | 'defensivo' | 'tatico' | 'covarde'

export type Character = {
  id: string
  worldId?: string
  name: string
  archetype: string
  actionAttributes: ActionAttributes
  battleAttributes: BattleAttributes
  advantages: string[]
  disadvantages: string[]
  attack: number
  defense: number
  skills: Skill[]
  battleSkills: BattleSkill[]          // tactical battle skills (separate from narrative skills)
  inventory: InventoryItem[]
  equippedItems: Record<EquipSlot, string | null>  // slot → equipmentId or null
  gold: number
  hp: number
  xp: number
  level: number
  status: string[]
  portraitUrl?: string
  appearance?: Appearance
  /** When true the character is benched and won't join the adventure */
  disabled?: boolean
}

export type ActionAttributes = {
  forca: number
  agilidade: number
  intelecto: number
  carisma: number
  vontade: number
  percepcao: number
}

export type BattleAttributes = {
  velocidade: number
  ataque: number
  defesa: number
  magia: number
}

export type Skill = {
  id: string
  name: string
  level: number
}

export type EquipmentType = 'arma' | 'armadura' | 'escudo' | 'pocao' | 'pergaminho' | 'amuleto' | 'anel' | 'ferramenta' | 'material' | 'chave' | 'tesouro'
export type ItemRarity = 'comum' | 'incomum' | 'raro' | 'epico' | 'lendario'
export type ItemUsageContext = 'batalha' | 'pre-acao' | 'ambos' | 'passivo' | 'narrativo'
export type EquipSlot = 'arma' | 'armadura' | 'escudo' | 'acessorio'

export type Equipment = {
  id: string
  name: string
  type: EquipmentType
  rarity: ItemRarity
  description: string
  narrativeEffect?: string           // flavor text for narrative impact
  usageContext: ItemUsageContext      // when this item can be used
  bonus: Record<string, number>       // passive stat bonus (action+battle attrs)
  actionBonus?: Partial<ActionAttributes>   // bonus when used pre-action
  battleBonus?: Partial<BattleAttributes>   // bonus in battle
  difficultyReduction?: number        // lowers difficulty when used pre-action (consumables/scrolls)
  hpRestore?: number                  // health restored (potions)
  sellPrice?: number                  // gold value (0 = cannot sell)
  consumable: boolean                 // destroyed after one use
  equippable: boolean                 // can occupy an equip slot
  stackable: boolean                  // can stack in inventory
  maxStack?: number                   // max stack size (default 99)
}

export type InventoryItem = {
  id: string
  equipmentId: string
  quantity: number
}

export type Reward = {
  id: string
  type: 'xp' | 'item' | 'moeda'
  amount: number
  itemId?: string
}

export type Drop = {
  id: string
  itemId: string
  chance: number
}

export type Npc = {
  id: string
  name: string
  role: string
  description: string
  personality?: string
  dialogue?: string[]          // sample dialogue lines
  questIds?: string[]          // quests this NPC can offer
  inventory?: string[]         // item ids for merchants
  lore?: string                // deeper backstory
}

export type Appearance = {
  genero: string
  raca: string
  idade: string
  pele: string
  cabelo: string
  corCabelo: string
  olhos: string
  altura: string
  traje: string
  acessorio: string
  detalhe: string
}

export type SaveState = {
  id: string
  worldId: string
  characterId: string
  currentLocationId: string
  activeQuestIds: string[]
  currentActId: string                // which act the player is on
  completedActIds: string[]           // acts fully completed
  completedMissionIds: string[]       // missions completed so far
  visitedLocationIds: string[]        // locations the player has already visited
  currentBattleId?: string             // battle in progress (if any)
  phase: 'idle' | 'ready' | 'playing' | 'ended'
  updatedAt: string
}

export type BattleState = {
  id: string
  worldId: string
  locationId: string
  combatants: BattleCombatant[]
  turnOrder: string[]                  // combatant IDs sorted by speed
  currentTurnIndex: number
  round: number
  phase: BattlePhase
  actionLog: BattleLogEntry[]
  terrain: TileType[][]                // 5x5 grid
  rewards?: BattleRewards
  updatedAt: string
}

export type BattlePhase =
  | 'intro'
  | 'player-turn'
  | 'enemy-turn'
  | 'dice-roll'
  | 'animation'
  | 'victory'
  | 'defeat'

export type TileType = 'normal' | 'blocked' | 'cover' | 'hazard'

export type GridPosition = { col: number; row: number }

export type BattleCombatant = {
  id: string
  name: string
  team: 'player' | 'enemy'
  position: GridPosition
  hp: number
  maxHp: number
  battleAttributes: BattleAttributes    // base attributes
  equipmentBonuses: Partial<BattleAttributes>
  statusEffects: StatusEffect[]
  actionPoints: number
  maxActionPoints: number               // 3 for all
  skills: BattleSkill[]
  isDefending: boolean
  hasAttacked: boolean                   // true after attack or skill — blocks defend
  hasDefended: boolean                   // true after defend — blocks attack/skill
  diceRollsRemaining: number            // 2 for players, 0 for enemies
  portraitUrl?: string
  /** Original character/enemy ID for persistence */
  sourceId: string
}

export type BattleSkillType = 'ataque' | 'cura' | 'buff' | 'debuff' | 'aoe' | 'controle'
export type BattleElement = 'fisico' | 'fogo' | 'gelo' | 'raio' | 'arcano' | 'sagrado' | 'sombrio'

export type BattleSkill = {
  id: string
  name: string
  description: string
  type: BattleSkillType
  element: BattleElement
  range: number                         // 1 = melee, 2+ = ranged
  aoeRadius: number                     // 0 = single target
  apCost: number                        // always 1
  maxUsesPerBattle: number              // 1-3 depending on power
  currentUses: number                   // decrements during battle
  damage?: { base: number; attribute: keyof BattleAttributes; scaling: number }
  healing?: number
  statusApply?: { effectId: string; chance: number }
  /** Lifetime usage tracking for progression */
  usageCount: number
  level: number                         // 1-5
  levelUpThreshold: number              // uses needed for next level
  /** Archetype that owns this skill (for catalog lookup) */
  archetype?: string
}

export type StatusEffectType = 'buff' | 'debuff' | 'dot' | 'hot' | 'control'

export type StatusEffect = {
  id: string
  name: string
  icon: string                          // lucide icon name or emoji
  type: StatusEffectType
  color: string                         // hex color for badge
  attribute?: keyof BattleAttributes
  value?: number                        // flat modifier
  percentModifier?: number              // percentage modifier (50 = +50%)
  damagePerTurn?: number
  healPerTurn?: number
  duration: number                      // turns remaining, -1 = permanent
  stackable: boolean
  maxStacks?: number
  currentStacks?: number
}

export type BattleLogEntry = {
  round: number
  actorId: string
  actorName: string
  actionType: 'attack' | 'defend' | 'skill' | 'item' | 'move' | 'flee' | 'dot' | 'hot' | 'dice'
  targetId?: string
  targetName?: string
  damage?: number
  healing?: number
  skillName?: string
  statusApplied?: string
  isCrit?: boolean
  isKill?: boolean
  text: string                          // human-readable description
}

export type BattleAction = {
  type: 'move' | 'attack' | 'defend' | 'skill' | 'item' | 'flee' | 'end-turn'
  actorId: string
  targetPosition?: GridPosition
  targetId?: string
  skillId?: string
  itemId?: string
}

export type DiceRollTarget = 'attack' | 'defense' | 'movement' | 'skill'

export type BattleRewards = {
  xp: number
  gold: number
  items: { id: string; name: string; type: string; rarity: string }[]
}

export type WorldRef = IdRef
export type LocationRef = IdRef
export type ActRef = IdRef
