export type IdRef = {
  id: string
}

export type World = {
  id: string
  title: string
  genre: string
  narrativeStyle?: string
  tone: string
  synopsis: string
  introNarrative?: string       // rich story introduction generated at world creation (up to 1000 chars)
  startingLocationId?: string   // location where the adventure begins (linked to Act 1)
  acts: Act[]
  locations: LocationRef[]
  finalObjective: string
  createdAt: string
  mapUrl?: string
}

export type ActMission = {
  id: string
  title: string
  description: string
  narrativeDirection: string   // what completing this advances in the story
  linkedNpcNames: string[]     // key NPCs involved
  completed: boolean
}

export type ActKeyNpc = {
  name: string
  role: string                 // e.g. "aliado", "vilao", "mentor", "mercador"
}

export type Act = {
  id: string
  title: string
  goal: string
  missions: ActMission[]       // min 3 per act — define when act is complete
  keyNpcs: ActKeyNpc[]         // important characters for this act
  linkedLocations: LocationRef[]
  requiredActId?: string       // previous act that must be completed first (null for Act 1)
}

export type Location = {
  id: string
  worldId?: string
  name: string
  type: string
  description?: string
  dangerLevel: number
  storyRelevance: 'main' | 'side'
  linkedActs: ActRef[]
  imageUrl?: string
  unlockedByActId?: string     // location is locked until this act is completed (undefined = always open)
}

/* ── Lightweight summaries (generated by LocationArchitect) ── */

export type NpcSummary = {
  id: string
  name: string
  role: string
  description: string
  narrativeEffect?: string
}

export type QuestSummary = {
  id: string
  title: string
  type: 'main' | 'side' | 'ambient'
  description: string
  narrativeEffect?: string
}

export type EnemySummary = {
  id: string
  name: string
  description: string
  narrativeEffect?: string
}

export type ItemSummary = {
  id: string
  name: string
  type: EquipmentType
  description: string
  narrativeEffect?: string
}

/* ── LocationContent (uses lightweight summaries) ── */

export type LocationContent = {
  id: string
  locationId: string
  npcs: NpcSummary[]
  quests: {
    main: QuestSummary[]
    side: QuestSummary[]
    ambient: QuestSummary[]
  }
  enemies: EnemySummary[]
  items: ItemSummary[]
  narrativeImpact: string
}

/* ── Full detail types (generated on-demand by dedicated agents) ── */

export type Quest = {
  id: string
  title: string
  type: 'main' | 'side' | 'ambient'
  description: string
  linkedActIds: string[]
  rewards: Reward[]
  impact: string
}

export type Enemy = {
  id: string
  name: string
  hp: number
  behavior: string
  attackPattern: string
  drops: Drop[]
}

export type Character = {
  id: string
  worldId?: string
  name: string
  archetype: string
  actionAttributes: ActionAttributes
  battleAttributes: BattleAttributes
  advantages: string[]
  disadvantages: string[]
  attack: number
  defense: number
  skills: Skill[]
  inventory: InventoryItem[]
  equippedItems: Record<EquipSlot, string | null>  // slot → equipmentId or null
  gold: number
  hp: number
  xp: number
  level: number
  status: string[]
  portraitUrl?: string
  appearance?: Appearance
  /** When true the character is benched and won't join the adventure */
  disabled?: boolean
}

export type ActionAttributes = {
  forca: number
  agilidade: number
  intelecto: number
  carisma: number
  vontade: number
  percepcao: number
}

export type BattleAttributes = {
  velocidade: number
  ataque: number
  defesa: number
  magia: number
}

export type Skill = {
  id: string
  name: string
  level: number
}

export type EquipmentType = 'arma' | 'armadura' | 'escudo' | 'pocao' | 'pergaminho' | 'amuleto' | 'anel' | 'ferramenta' | 'material' | 'chave' | 'tesouro'
export type ItemRarity = 'comum' | 'incomum' | 'raro' | 'epico' | 'lendario'
export type ItemUsageContext = 'batalha' | 'pre-acao' | 'ambos' | 'passivo' | 'narrativo'
export type EquipSlot = 'arma' | 'armadura' | 'escudo' | 'acessorio'

export type Equipment = {
  id: string
  name: string
  type: EquipmentType
  rarity: ItemRarity
  description: string
  narrativeEffect?: string           // flavor text for narrative impact
  usageContext: ItemUsageContext      // when this item can be used
  bonus: Record<string, number>       // passive stat bonus (action+battle attrs)
  actionBonus?: Partial<ActionAttributes>   // bonus when used pre-action
  battleBonus?: Partial<BattleAttributes>   // bonus in battle
  difficultyReduction?: number        // lowers difficulty when used pre-action (consumables/scrolls)
  hpRestore?: number                  // health restored (potions)
  sellPrice?: number                  // gold value (0 = cannot sell)
  consumable: boolean                 // destroyed after one use
  equippable: boolean                 // can occupy an equip slot
  stackable: boolean                  // can stack in inventory
  maxStack?: number                   // max stack size (default 99)
}

export type InventoryItem = {
  id: string
  equipmentId: string
  quantity: number
}

export type Reward = {
  id: string
  type: 'xp' | 'item' | 'moeda'
  amount: number
  itemId?: string
}

export type Drop = {
  id: string
  itemId: string
  chance: number
}

export type Npc = {
  id: string
  name: string
  role: string
  description: string
  personality?: string
  dialogue?: string[]          // sample dialogue lines
  questIds?: string[]          // quests this NPC can offer
  inventory?: string[]         // item ids for merchants
  lore?: string                // deeper backstory
}

export type Appearance = {
  genero: string
  raca: string
  idade: string
  pele: string
  cabelo: string
  corCabelo: string
  olhos: string
  altura: string
  traje: string
  acessorio: string
  detalhe: string
}

export type SaveState = {
  id: string
  worldId: string
  characterId: string
  currentLocationId: string
  activeQuestIds: string[]
  currentActId: string                // which act the player is on
  completedActIds: string[]           // acts fully completed
  completedMissionIds: string[]       // missions completed so far
  phase: 'idle' | 'ready' | 'playing' | 'ended'
  updatedAt: string
}

export type BattleState = {
  id: string
  enemyIds: string[]
  playerHp: number
  turn: number
  updatedAt: string
}

export type WorldRef = IdRef
export type LocationRef = IdRef
export type ActRef = IdRef
